# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 TRUSCA contributors
"""
Admin user-management service — Phase 4 PR #13.

Pure DB I/O for the ``/v1/admin/users/*`` HTTP surface. The router is a thin
adapter that translates HTTP shapes into these calls and turns the domain
exceptions below into RFC 7807 responses.

Safety contracts (CLAUDE.md "조직/팀/권한 모델" + PR #13 spec §4.2):
  - Demoting / deactivating the *last* active super_admin is rejected.
    422 with extension ``last_super_admin_protected = true``.
  - The actor cannot mutate their own role / activation state — there is
    no recovery path if the only super_admin locks themselves out.
    422 with extension ``cannot_modify_self = true``.
  - Password-reset tokens are bcrypt-hashed; the plaintext is generated by
    the issuer endpoint and intentionally discarded after issuance. Phase 6
    PR #18 wires the email channel that delivers the plaintext.
  - Single-pending-token policy: issuing a new reset token marks any
    previous unused / non-expired / non-invalidated rows for the same user
    as ``invalidated_at = now()``.

Audit hand-off:
  Mutating ORM rows is enough — the SQLAlchemy ``before_flush`` listener
  in ``core.audit`` produces the audit_logs row automatically. Sensitive
  columns (``hashed_password``, ``token_hash``) are auto-masked in the diff.
  Service code therefore must never call ``session.add(AuditLog(...))``.
"""

from __future__ import annotations

import secrets
import uuid
from datetime import UTC, datetime, timedelta

import structlog
from sqlalchemy import func, or_, select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload
from starlette.concurrency import run_in_threadpool

from core.config import default_member_role
from core.security import CurrentUser, forget_principal, hash_password
from core.sql_safety import escape_like
from models import Membership, PasswordResetToken, RefreshToken, Scan, Team, User
from schemas.admin import (
    AdminUserCreateIn,
    AdminUserDetail,
    AdminUserListItem,
    AdminUserListPage,
    AdminUserRoleUpdate,
    BulkResultOut,
    BulkRowResult,
    TeamMembershipPublic,
)
from services.csv_export import CSV_BOM, csv_line

log = structlog.get_logger("admin.user.service")


# ---------------------------------------------------------------------------
# Domain exceptions
# ---------------------------------------------------------------------------


class AdminUserError(Exception):
    """Base class for admin-user errors. Each carries an HTTP status."""

    status_code: int = 400
    title: str = "Admin User Error"
    extensions: dict[str, object] = {}


class AdminUserNotFound(AdminUserError):
    status_code = 404
    title = "User Not Found"


class LastSuperAdminProtected(AdminUserError):
    status_code = 422
    title = "Last Super Admin Protected"
    extensions = {"last_super_admin_protected": True}


class CannotModifySelf(AdminUserError):
    status_code = 422
    title = "Cannot Modify Self"
    extensions = {"cannot_modify_self": True}


class InvalidRoleAssignment(AdminUserError):
    status_code = 422
    title = "Invalid Role Assignment"


class TeamNotFound(AdminUserError):
    """
    422 instead of 500 when a role-update references a non-existent team.

    Security-reviewer F9: previously a missing ``team_id`` (e.g. the team was
    deleted between the admin opening the drawer and clicking save) would
    raise an SQLAlchemy ``IntegrityError`` from the FK constraint and bubble
    up as a 500. The 500 leaks "an unhandled error occurred" to the caller
    AND skips the RFC 7807 envelope. We now translate the case at the
    service boundary to a 422 + Problem Details with extension
    ``{"team_id": "<uuid>"}`` so the UI can highlight the offending field.

    Two-layer guard:
      1. Preflight ``SELECT id FROM teams WHERE id = :team_id`` — fast path
         that catches the common "stale UUID" case BEFORE the membership
         insert.
      2. ``IntegrityError`` catch around the commit — closes the race
         where the team is deleted concurrently AFTER our preflight but
         BEFORE our commit. Both layers surface the same Problem Details.
    """

    status_code = 422
    title = "Team Not Found"

    def __init__(self, message: str, *, team_id: uuid.UUID | None = None) -> None:
        super().__init__(message)
        # Per-instance extension dict so the admin router can echo
        # ``team_id`` as a top-level snake_case Problem-Details field
        # without leaking other admin errors' extensions across instances.
        # The class-level ``extensions = {}`` default still applies to
        # other AdminUserError subclasses untouched.
        self.extensions = {"team_id": str(team_id)} if team_id is not None else {}


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _now() -> datetime:
    return datetime.now(tz=UTC)


def _is_team_fk_violation(exc: IntegrityError) -> bool:
    """
    Identify the FK-violation flavour of ``IntegrityError`` we want to
    translate to ``TeamNotFound``.

    Postgres' SQLSTATE for foreign-key violation is ``23503``. We prefer the
    precise ``orig.diag.constraint_name`` check (L2 — asyncpg / psycopg expose
    the pg_constraint name via the ``diag`` descriptor) over string-matching
    the raw error message, which is locale-dependent and can match other FK
    names accidentally. The text-match on ``str(orig)`` is kept as a fallback
    for drivers that do not expose ``diag``.
    """
    orig = getattr(exc, "orig", None)
    pgcode = getattr(orig, "pgcode", None) or getattr(orig, "sqlstate", None)
    if pgcode != "23503":
        return False

    # Prefer structural constraint-name check (asyncpg/psycopg diag object).
    diag = getattr(orig, "diag", None)
    constraint_name: str | None = getattr(diag, "constraint_name", None)
    if constraint_name is not None:
        return "team_id" in constraint_name or constraint_name.startswith("memberships_team")

    # Fallback: text-match for drivers without diag (e.g. unit-test stubs).
    message = str(orig).lower()
    return "team_id" in message or "teams" in message


def _is_last_super_admin_violation(exc: IntegrityError) -> bool:
    """
    Identify the trigger-raised CHECK violation from migration 0013
    (``enforce_last_super_admin``).

    SQLSTATE 23514 (check_violation). We text-match the function-raised
    message because Postgres does not attach a constraint_name to RAISE
    EXCEPTION statements — the diag.constraint_name field is empty for
    plpgsql-raised exceptions. The message string ``last active super_admin
    cannot be removed or demoted`` is part of the migration contract;
    changing it requires updating both this matcher and the migration.
    """
    orig = getattr(exc, "orig", None)
    pgcode = getattr(orig, "pgcode", None) or getattr(orig, "sqlstate", None)
    if pgcode != "23514":
        return False
    message = str(orig).lower()
    return "last active super_admin" in message


async def _lock_and_count_active_super_admins(session: AsyncSession) -> int:
    """
    Acquire a row-level lock on the active-super-admin set and return the count.

    Closes the TOCTOU race between SELECT-then-mutate that a plain
    ``SELECT count()`` would expose: two concurrent demote/deactivate
    transactions could each read ``count == 2``, both pass the ``> 1`` guard,
    and then both commit, dropping the active super_admin count to zero.

    The locking SELECT pulls every (is_active, is_superuser) row with
    ``FOR UPDATE``. Postgres holds those row locks until the calling
    transaction commits or rolls back — so a second concurrent call against
    any of the same rows blocks until the first finishes, at which point
    the second sees the post-commit count and the guard fires correctly.

    Lock order convention (also documented in admin_team_service):
      ``users (is_superuser=true AND is_active=true)`` is always locked
    BEFORE any ``memberships`` rows in the same transaction, to keep a
    consistent global lock order across the two admin services and avoid
    deadlocks on cross-service operations.

    Reference: the same optimistic-concurrency pattern; it
    matches ``vulnerability_service.py:309`` (``with_for_update`` on the
    finding row before the optimistic-concurrency compare-and-swap).
    """
    # Pull the rows with FOR UPDATE so Postgres takes the row locks. We
    # then count from the materialized list — using a separate
    # ``SELECT count()`` would emit a second statement that does NOT take
    # the same locks. ``scalars().all()`` consumes the result and forces
    # the lock to be acquired.
    locked = (
        (
            await session.execute(
                select(User)
                .where(User.is_active.is_(True), User.is_superuser.is_(True))
                .with_for_update()
            )
        )
        .scalars()
        .all()
    )
    return len(locked)


async def _load_user_with_memberships(
    session: AsyncSession,
    user_id: uuid.UUID,
    *,
    allow_service_account: bool = False,
) -> User:
    """
    Fetch the user with its memberships eagerly loaded.

    Service accounts are excluded by default, and the exclusion lives here
    rather than in each operation on purpose. Only the list was filtered at
    first, and the five operations that share this loader were not: the role
    endpoint could make an automation identity a super admin and grant it
    memberships in other teams, and the list filter then hid the result from
    the one screen anybody sweeps afterwards. A default on the shared loader
    is the version that cannot be forgotten one call site at a time.

    404 rather than 403, matching the list: to this surface a service account
    simply is not a user.

    If the User is already in the session's identity map (likely after a
    prior mutation in this same call chain), we refresh the memberships
    collection explicitly so the response sees the post-commit state.
    Without this step a User that was loaded earlier — e.g. in
    update_user_role before we added a Membership row — would be served
    from the identity map with a stale empty memberships collection.
    """
    stmt = select(User).where(User.id == user_id).options(selectinload(User.memberships))
    if not allow_service_account:
        stmt = stmt.where(User.is_service_account.is_(False))
    user = (await session.execute(stmt)).scalar_one_or_none()
    if user is None:
        raise AdminUserNotFound(f"user {user_id} not found")
    # Even though the SELECT requested memberships eagerly, SQLAlchemy may
    # serve the User from the identity map; an explicit refresh of the
    # collection guarantees we see fresh rows from any prior commit in
    # this session.
    await session.refresh(user, attribute_names=["memberships"])
    return user


async def _team_name_map(session: AsyncSession, team_ids: list[uuid.UUID]) -> dict[uuid.UUID, str]:
    if not team_ids:
        return {}
    stmt = select(Team.id, Team.name).where(Team.id.in_(team_ids))
    rows = (await session.execute(stmt)).all()
    return {row[0]: row[1] for row in rows}


async def _scan_count_for_user(session: AsyncSession, user_id: uuid.UUID) -> int:
    stmt = select(func.count()).select_from(Scan).where(Scan.requested_by_user_id == user_id)
    return int((await session.execute(stmt)).scalar_one())


# ---------------------------------------------------------------------------
# List
# ---------------------------------------------------------------------------


async def list_users(
    session: AsyncSession,
    *,
    actor: CurrentUser,  # noqa: ARG001 — kept for symmetry with other admin services
    page: int = 1,
    page_size: int = 50,
    role: str | None = None,
    active: bool | None = None,
    search: str | None = None,
) -> AdminUserListPage:
    """
    Return a page of users (paginated, filterable).

    - ``role`` filters by highest-effective role (super_admin = is_superuser;
      team_admin / developer = exists membership with that role; the filter
      is a coarse "user has at least one membership of this kind"). When
      role is ``super_admin`` we filter on ``is_superuser=true`` directly.
    - ``active`` filters by ``is_active`` exactly.
    - ``search`` is bounded substring ILIKE on email or full_name (max 255
      chars to bound the query cost).
    """
    page = max(page, 1)
    page_size = max(min(page_size, 200), 1)

    # People only. A service account in the user list would invite the actions
    # this list offers, and those actions are wrong for it: there is nobody to
    # email a reset to, and deactivating it from here is a pipeline outage that
    # reads on screen as tidying up a leaver. Service accounts are managed on
    # the integrations page, next to the keys they hold.
    base = select(User).where(User.is_service_account.is_(False))
    count_base = (
        select(func.count())
        .select_from(User)
        .where(User.is_service_account.is_(False))
    )

    if active is not None:
        base = base.where(User.is_active.is_(active))
        count_base = count_base.where(User.is_active.is_(active))

    if role == "super_admin":
        base = base.where(User.is_superuser.is_(True))
        count_base = count_base.where(User.is_superuser.is_(True))
    elif role in ("team_admin", "developer", "viewer"):
        sub = select(Membership.user_id).where(Membership.role == role).scalar_subquery()
        base = base.where(User.id.in_(sub))
        count_base = count_base.where(User.id.in_(sub))

    if search and search.strip():
        # Bounded substring search; the inputs are already capped at 255 in
        # the route layer (Query(max_length=255)). Search is intentionally
        # case-insensitive on email (CITEXT-friendly) and full_name.
        # Wildcards are escaped so a literal '%' cannot widen the match to
        # every user in the deployment (S1-2).
        like = f"%{escape_like(search.strip())}%"
        predicate = or_(
            User.email.ilike(like, escape="\\"),
            User.full_name.ilike(like, escape="\\"),
        )
        base = base.where(predicate)
        count_base = count_base.where(predicate)

    total = int((await session.execute(count_base)).scalar_one())

    rows_stmt = (
        base.order_by(User.created_at.desc(), User.id.desc())
        .limit(page_size)
        .offset((page - 1) * page_size)
    )
    rows = list((await session.execute(rows_stmt)).scalars().all())

    # H-2: membership rollup for the page (one aggregate query, not N) so the
    # list can render the effective role + team count without the drawer.
    rollup: dict[uuid.UUID, tuple[int, bool]] = {}
    user_ids = [u.id for u in rows]
    if user_ids:
        agg = await session.execute(
            select(
                Membership.user_id,
                func.count(Membership.id),
                func.bool_or(Membership.role == "team_admin"),
            )
            .where(Membership.user_id.in_(user_ids))
            .group_by(Membership.user_id)
        )
        for uid, member_count, has_team_admin in agg.all():
            rollup[uid] = (int(member_count), bool(has_team_admin))

    def _effective_role(u: User) -> str:
        if u.is_superuser:
            return "super_admin"
        _, has_team_admin = rollup.get(u.id, (0, False))
        return "team_admin" if has_team_admin else "developer"

    items = [
        AdminUserListItem(
            id=u.id,
            email=u.email,
            full_name=u.full_name,
            is_active=u.is_active,
            is_superuser=u.is_superuser,
            role=_effective_role(u),  # type: ignore[arg-type]
            team_count=rollup.get(u.id, (0, False))[0],
            last_login_at=u.last_login_at,
            created_at=u.created_at,
        )
        for u in rows
    ]

    return AdminUserListPage(
        items=items,
        total=total,
        page=page,
        page_size=page_size,
    )


# ---------------------------------------------------------------------------
# Get detail
# ---------------------------------------------------------------------------


async def get_user_detail(
    session: AsyncSession,
    *,
    actor: CurrentUser,  # noqa: ARG001
    user_id: uuid.UUID,
) -> AdminUserDetail:
    user = await _load_user_with_memberships(session, user_id)

    memberships = list(user.memberships)
    team_names = await _team_name_map(session, [m.team_id for m in memberships])
    scan_count = await _scan_count_for_user(session, user_id)

    return AdminUserDetail(
        id=user.id,
        email=user.email,
        full_name=user.full_name,
        is_active=user.is_active,
        is_superuser=user.is_superuser,
        last_login_at=user.last_login_at,
        created_at=user.created_at,
        updated_at=user.updated_at,
        scan_count=scan_count,
        memberships=[
            TeamMembershipPublic(
                team_id=m.team_id,
                team_name=team_names.get(m.team_id, ""),
                role=m.role,
            )
            for m in memberships
        ],
    )


# ---------------------------------------------------------------------------
# Update role
# ---------------------------------------------------------------------------


async def update_user_role(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    user_id: uuid.UUID,
    payload: AdminUserRoleUpdate,
) -> AdminUserDetail:
    """
    Set the user's role.

    Semantics:
      - ``role == "super_admin"`` -> ``user.is_superuser = True``. Existing
        memberships are not touched (the super_admin role is global; team
        memberships are independent).
      - ``role in {"team_admin", "developer"}`` -> ``user.is_superuser = False``
        AND upsert ``Membership(user_id, team_id, role)``. ``team_id`` is
        required.

    Safety: rejects (422) when the change would demote the last active
    super_admin or when the actor is the target user.
    """
    if user_id == actor.id:
        raise CannotModifySelf("cannot modify your own role")

    user = await _load_user_with_memberships(session, user_id)

    target_role = payload.role
    target_team_id = payload.team_id

    if target_role == "super_admin":
        # Promotion to super_admin (or no-op if already super_admin).
        user.is_superuser = True
        user.updated_at = _now()
    else:
        if target_team_id is None:
            raise InvalidRoleAssignment("team_id is required when role is team_admin or developer")

        # F9 — preflight: the team must exist BEFORE we let the membership
        # insert race a deleted-team CASCADE. The IntegrityError catch on
        # commit is the second-line defence for the rare delete-during-
        # commit window, but the preflight catches the common "stale UUID"
        # case at a clean boundary with no rollback noise.
        team_exists = (
            await session.execute(select(Team.id).where(Team.id == target_team_id))
        ).scalar_one_or_none()
        if team_exists is None:
            raise TeamNotFound(
                f"team {target_team_id} does not exist",
                team_id=target_team_id,
            )

        # If we are demoting *from* super_admin, make sure we are not
        # removing the last lockout-prevention seat. Take a row-level lock
        # on the entire active-super-admin set BEFORE the count check so
        # two concurrent demote requests serialize through Postgres
        # instead of both passing an optimistic ``count > 1`` check
        # (CWE-367 TOCTOU; see _lock_and_count_active_super_admins).
        if user.is_superuser:
            count = await _lock_and_count_active_super_admins(session)
            # The user being demoted is counted; demoting them takes the
            # count to (count - 1). Reject when that would hit zero.
            if user.is_active and count <= 1:
                raise LastSuperAdminProtected("cannot demote the last active super_admin")
            user.is_superuser = False

        # Upsert the membership row.
        existing = next(
            (m for m in user.memberships if m.team_id == target_team_id),
            None,
        )
        if existing is None:
            session.add(
                Membership(
                    user_id=user.id,
                    team_id=target_team_id,
                    role=target_role,
                )
            )
        else:
            existing.role = target_role
            existing.updated_at = _now()

        user.updated_at = _now()

    try:
        await session.commit()
    except IntegrityError as exc:
        # F9 — race window: the team was deleted between our preflight
        # SELECT and the membership INSERT. The FK CASCADE on team delete
        # would normally take both rows together, but the membership row
        # we're inserting was not present at that point. Translate the FK
        # violation to a 422 with the same Problem Details shape as the
        # preflight. Other IntegrityErrors (uniqueness on the membership
        # PK, etc.) re-raise — those are real bugs, not user errors.
        await session.rollback()
        if target_team_id is not None and _is_team_fk_violation(exc):
            raise TeamNotFound(
                f"team {target_team_id} does not exist",
                team_id=target_team_id,
            ) from exc
        # A5 (sys-bug-u&t-1) — depth-in-defence: the application guard
        # (_lock_and_count_active_super_admins above) should always trip
        # first under normal flow. The DB trigger from migration 0013
        # only fires when something bypasses that guard (e.g. a future
        # endpoint that forgets to call the locking count). Translate the
        # 23514 to the same Problem Details shape so the API contract is
        # invariant of which layer caught the bypass.
        if _is_last_super_admin_violation(exc):
            raise LastSuperAdminProtected(
                "cannot demote the last active super_admin"
            ) from exc
        raise
    # Their grade just changed, so any principal cached from the old one is
    # wrong. Bounded by the lifetime either way; this is what makes the
    # administrator's own next request show the new grade.
    forget_principal(user_id)
    log.info(
        "admin.user.role_changed",
        actor_id=str(actor.id),
        target_user_id=str(user_id),
        new_role=target_role,
        team_id=str(target_team_id) if target_team_id else None,
    )

    # Reload with memberships for the response.
    return await get_user_detail(session, actor=actor, user_id=user_id)


# ---------------------------------------------------------------------------
# Activate / deactivate
# ---------------------------------------------------------------------------


async def deactivate_user(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    user_id: uuid.UUID,
) -> AdminUserDetail:
    """
    Set ``is_active = False`` and revoke every live refresh token.

    Safety:
      - Cannot deactivate self (cannot_modify_self=true).
      - Cannot deactivate the last active super_admin (last_super_admin_protected=true).
    """
    if user_id == actor.id:
        raise CannotModifySelf("cannot deactivate yourself")

    user = await _load_user_with_memberships(session, user_id)
    if not user.is_active:
        # Already deactivated — idempotent no-op. Still emit the detail.
        return await get_user_detail(session, actor=actor, user_id=user_id)

    if user.is_superuser:
        # Lock the active-super-admin row set inside this transaction
        # before the count check so two concurrent deactivations cannot
        # both pass the ``count > 1`` guard. CWE-367 TOCTOU fix.
        count = await _lock_and_count_active_super_admins(session)
        if count <= 1:
            raise LastSuperAdminProtected("cannot deactivate the last active super_admin")

    now = _now()
    user.is_active = False
    user.updated_at = now

    # Revoke every live refresh token so the deactivated user can no longer
    # rotate even if they hold a fresh refresh cookie. We pull live rows and
    # mutate them so the audit listener captures each revocation.
    live_tokens = (
        (
            await session.execute(
                select(RefreshToken).where(
                    RefreshToken.user_id == user_id,
                    RefreshToken.revoked_at.is_(None),
                )
            )
        )
        .scalars()
        .all()
    )
    for token in live_tokens:
        token.revoked_at = now
        token.revoked_reason = "logout"

    try:
        await session.commit()
    except IntegrityError as exc:
        # A5 depth-in-defence: same translation as update_user_role above.
        # Application guard already blocked the last-active deactivation in
        # the typical path; this branch covers a service-bypassing call.
        await session.rollback()
        if _is_last_super_admin_violation(exc):
            raise LastSuperAdminProtected(
                "cannot deactivate the last active super_admin"
            ) from exc
        raise
    forget_principal(user_id)
    log.info(
        "admin.user.deactivated",
        actor_id=str(actor.id),
        target_user_id=str(user_id),
        revoked_token_count=len(live_tokens),
    )

    return await get_user_detail(session, actor=actor, user_id=user_id)


async def activate_user(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    user_id: uuid.UUID,
) -> AdminUserDetail:
    """Set ``is_active = True``. Idempotent on already-active users."""
    user = await _load_user_with_memberships(session, user_id)
    if user.is_active:
        return await get_user_detail(session, actor=actor, user_id=user_id)

    user.is_active = True
    user.updated_at = _now()
    await session.commit()
    forget_principal(user_id)
    log.info(
        "admin.user.activated",
        actor_id=str(actor.id),
        target_user_id=str(user_id),
    )
    return await get_user_detail(session, actor=actor, user_id=user_id)


# ---------------------------------------------------------------------------
# Password reset
# ---------------------------------------------------------------------------


# Hard-coded TTL for now. Phase 6 PR #18 may make this env-driven once the
# email channel ships. CLAUDE.md core rule #11 forbids reading env vars at
# module import time, so when that change happens it will move to a runtime
# `os.getenv()` inside this function.
_PASSWORD_RESET_TTL = timedelta(hours=1)


async def initiate_password_reset(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    user_id: uuid.UUID,
) -> uuid.UUID:
    """
    Generate a one-shot reset token, persist its bcrypt hash, return the row id.

    The plaintext token is returned to the caller (the HTTP route) only so
    Phase 6 PR #18 can plug an email sender in front of this service. The
    current router discards it after logging — see api/v1/admin/users.py.

    Returns the new ``password_reset_tokens.id``. The plaintext is NOT
    returned: this service is responsible for hashing + persisting and the
    route is responsible for the side-channel delivery.
    """
    user = await _load_user_with_memberships(session, user_id)
    now = _now()

    # Single-pending-token policy: invalidate any prior live tokens for this
    # user before issuing a new one. We pull rows and mutate so the audit
    # listener captures each invalidation.
    live = (
        (
            await session.execute(
                select(PasswordResetToken).where(
                    PasswordResetToken.user_id == user_id,
                    PasswordResetToken.used_at.is_(None),
                    PasswordResetToken.invalidated_at.is_(None),
                    PasswordResetToken.expires_at > now,
                )
            )
        )
        .scalars()
        .all()
    )
    for prior in live:
        prior.invalidated_at = now

    plaintext = secrets.token_urlsafe(32)
    token_hash = hash_password(plaintext)
    row = PasswordResetToken(
        user_id=user.id,
        token_hash=token_hash,
        expires_at=now + _PASSWORD_RESET_TTL,
    )
    session.add(row)
    await session.commit()
    await session.refresh(row)

    log.info(
        "admin.user.password_reset_initiated",
        actor_id=str(actor.id),
        target_user_id=str(user_id),
        reset_token_id=str(row.id),
        invalidated_count=len(live),
    )

    # Plaintext is intentionally never returned. The model's id is enough
    # for the route to log + emit the audit event.
    del plaintext  # explicit drop — make the discard intent obvious
    return row.id


__all__ = [
    "AdminUserError",
    "AdminUserNotFound",
    "CannotModifySelf",
    "InvalidRoleAssignment",
    "LastSuperAdminProtected",
    "TeamNotFound",
    "activate_user",
    "deactivate_user",
    "get_user_detail",
    "initiate_password_reset",
    "list_users",
    "update_user_role",
]


# ---------------------------------------------------------------------------
# Creating people, one at a time and in batches (N4)
# ---------------------------------------------------------------------------
#
# The batch calls the single one. That is the whole design, and it is the
# answer to the way this feature usually breaks: a bulk path that writes rows
# itself, skipping the validation the single path performs and the audit rows
# its mutations produce, so an import quietly admits accounts the API would
# have refused one at a time.


class EmailAlreadyTaken(AdminUserError):
    status_code = 409
    title = "Email Already Registered"


#: What goes in ``hashed_password`` for an account that signs in elsewhere.
#:
#: The crypt(3) convention for "this account has no password". Not a bcrypt
#: hash of a random secret, which is what this was first: that costs a
#: cost-12 hash per row at import time for a value nobody will ever verify
#: against, and 500 of them run one after another. ``verify_password``
#: returns False for a hash it cannot parse, so a sentinel bcrypt refuses to
#: read is refused earlier and more cheaply than one it reads and rejects.
_NO_PASSWORD = "!"  # noqa: S105 (a refusal marker, not a credential)


def _is_duplicate_email(exc: IntegrityError) -> bool:
    """Whether this violation is the unique index on the address.

    Named rather than assumed. The first version treated every integrity
    failure that was not the team foreign key as a duplicate address, so a
    constraint added later would have been reported to the operator as an
    email collision on a row whose address was fine.
    """
    constraint = getattr(getattr(exc.orig, "diag", None), "constraint_name", None)
    if isinstance(constraint, str):
        return "email" in constraint
    return "users_email" in str(exc.orig)


async def create_user(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    payload: AdminUserCreateIn,
) -> AdminUserDetail:
    """Add one person.

    Distinct from public registration in two ways that matter. The team is
    named rather than invented, because an administrator adding somebody to an
    organization knows where they belong and does not want a personal team per
    head. And a password is optional: on a deployment where people arrive
    through an identity provider, an account with no usable password is the
    correct account, not a half-made one.
    """
    email = str(payload.email).strip().lower()
    # Explicit fallback rather than one inside the setting: an account an
    # administrator adds has always carried ``developer``, and the other
    # caller of this setting has always carried something else.
    role = payload.role or default_member_role() or "developer"

    if payload.team_id is not None:
        team = (
            await session.execute(select(Team.id).where(Team.id == payload.team_id))
        ).scalar_one_or_none()
        if team is None:
            raise TeamNotFound(f"team {payload.team_id} not found", team_id=payload.team_id)

    existing = (
        await session.execute(select(User.id).where(User.email == email))
    ).scalar_one_or_none()
    if existing is not None:
        raise EmailAlreadyTaken(f"email already registered: {email}")

    user = User(
        email=email,
        hashed_password=(
            # Off the event loop: bcrypt at cost 12 is a quarter of a second,
            # and the batch path runs this once per row while the worker
            # serves nothing else.
            await run_in_threadpool(hash_password, payload.password)
            if payload.password is not None
            else _NO_PASSWORD
        ),
        full_name=payload.full_name,
        is_active=True,
        is_superuser=False,
        is_verified=False,
    )
    session.add(user)
    try:
        await session.flush()
    except IntegrityError as exc:
        # The check above lost a race. Same answer either way.
        await session.rollback()
        raise EmailAlreadyTaken(f"email already registered: {email}") from exc

    if payload.team_id is not None:
        session.add(Membership(user_id=user.id, team_id=payload.team_id, role=role))

    try:
        await session.commit()
    except IntegrityError as exc:
        await session.rollback()
        if _is_team_fk_violation(exc):
            raise TeamNotFound(
                f"team {payload.team_id} not found", team_id=payload.team_id
            ) from exc
        if _is_duplicate_email(exc):
            raise EmailAlreadyTaken(f"email already registered: {email}") from exc
        # Anything else is a constraint nobody here knows about. Reporting it
        # as a taken address would tell the operator something false about
        # their own file; letting it out makes it a logged failure with a
        # trace, which is what an unrecognised constraint deserves.
        raise

    log.info(
        "admin.user.created",
        actor_id=str(actor.id),
        target_user_id=str(user.id),
        team_id=str(payload.team_id) if payload.team_id else None,
        role=role if payload.team_id else None,
        has_password=payload.password is not None,
    )
    return await get_user_detail(session, actor=actor, user_id=user.id)


async def bulk_create_users(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    rows: list[AdminUserCreateIn],
) -> BulkResultOut:
    """Run every row through :func:`create_user` and report each one.

    Rows are independent. One bad address does not roll back the people
    before it, because an administrator importing a directory export wants the
    397 that were fine and a list of the three that were not, rather than an
    error and a file to bisect.
    """
    results: list[BulkRowResult] = []
    for index, row in enumerate(rows):
        identifier = str(row.email).strip().lower()
        try:
            detail = await create_user(session, actor=actor, payload=row)
        except AdminUserError as exc:
            results.append(
                BulkRowResult(
                    index=index,
                    identifier=identifier,
                    status="failed",
                    reason=_reason_for(exc),
                    detail=str(exc),
                )
            )
            continue
        except Exception:
            # One row that fails in a way nobody anticipated must not take the
            # report with it. create_user commits per row, so an exception
            # escaping here would leave the rows before it created and answer
            # the administrator with no list of what happened.
            #
            # No ``str(exc)``: this is the branch where a driver message could
            # reach the response, and the trace belongs in the log instead.
            await session.rollback()
            log.exception("admin.user.bulk_row_failed", index=index)
            results.append(
                BulkRowResult(
                    index=index,
                    identifier=identifier,
                    status="failed",
                    reason="failed",
                )
            )
            continue
        results.append(
            BulkRowResult(
                index=index,
                identifier=identifier,
                status="created",
                user_id=detail.id,
            )
        )

    succeeded = sum(1 for row in results if row.status != "failed")
    return BulkResultOut(
        total=len(results),
        succeeded=succeeded,
        failed=len(results) - succeeded,
        results=results,
    )


async def bulk_deactivate_users(
    session: AsyncSession,
    *,
    actor: CurrentUser,
    user_ids: list[uuid.UUID],
) -> BulkResultOut:
    """Deactivate each id through :func:`deactivate_user`.

    The protections stay where they are: an administrator cannot deactivate
    themselves or the last super admin, and putting either id in a list does
    not change that. Both come back as one failed row rather than refusing the
    batch, which is the same reading as above.

    Somebody already inactive is reported as skipped rather than deactivated,
    because a run that says it deactivated 40 people when 12 were already gone
    is a number an administrator will act on.
    """
    results: list[BulkRowResult] = []
    for index, user_id in enumerate(user_ids):
        was_active = (
            await session.execute(select(User.is_active).where(User.id == user_id))
        ).scalar_one_or_none()
        try:
            await deactivate_user(session, actor=actor, user_id=user_id)
        except AdminUserError as exc:
            results.append(
                BulkRowResult(
                    index=index,
                    identifier=str(user_id),
                    status="failed",
                    reason=_reason_for(exc),
                    detail=str(exc),
                )
            )
            continue
        except Exception:
            await session.rollback()
            log.exception("admin.user.bulk_deactivate_row_failed", index=index)
            results.append(
                BulkRowResult(
                    index=index,
                    identifier=str(user_id),
                    status="failed",
                    reason="failed",
                )
            )
            continue
        results.append(
            BulkRowResult(
                index=index,
                identifier=str(user_id),
                status="deactivated" if was_active else "skipped",
                user_id=user_id,
            )
        )

    succeeded = sum(1 for row in results if row.status != "failed")
    return BulkResultOut(
        total=len(results),
        succeeded=succeeded,
        failed=len(results) - succeeded,
        results=results,
    )


#: Exception class to the token the frontend translates. The Problem Details
#: ``detail`` is English and always will be, and this is a table an
#: administrator reads a row at a time to decide what to fix.
_BULK_REASONS: dict[type[AdminUserError], str] = {
    EmailAlreadyTaken: "email_taken",
    TeamNotFound: "team_not_found",
    AdminUserNotFound: "not_found",
    CannotModifySelf: "cannot_modify_self",
    LastSuperAdminProtected: "last_super_admin",
    InvalidRoleAssignment: "invalid_role",
}


def _reason_for(exc: AdminUserError) -> str:
    return _BULK_REASONS.get(type(exc), "failed")


#: Rows an export will build before refusing. The roster is the one table
#: whose size is the deployment's headcount rather than its activity, so a
#: directory-scale install is the ordinary case rather than the extreme one.
_ROSTER_EXPORT_LIMIT = 50_000


class RosterExportTooLarge(AdminUserError):
    """More people than an export is willing to hold in memory at once.

    Raised before the first row is built, so the operator gets an error rather
    than a file that is silently short. Nothing inside a truncated CSV says it
    is truncated, which is what makes it worse than a refusal.
    """

    status_code = 413
    title = "Export Too Large"
    extensions = {"roster_export_too_large": True}


async def export_users_csv(
    session: AsyncSession,
    *,
    actor: CurrentUser,
) -> str:
    """Every person as CSV, in the shape the bulk import accepts back.

    Round-tripping is the point: an export that cannot be edited and fed back
    in is a report, and what an administrator wants here is the roster they
    already have plus the ten people who joined.

    No password column, in either direction of the round trip. An export
    carrying credentials would put every account in the deployment into a
    spreadsheet in somebody's downloads folder.

    Cells go through the shared ``csv_cell``: a name beginning ``=`` is a live
    formula the moment a spreadsheet opens the file, and a name is something
    an unauthenticated person can choose at registration. The same helper
    supplies the byte-order mark, without which Excel on a Korean locale reads
    every row as mojibake.
    """
    total = int(
        (
            await session.execute(
                select(func.count())
                .select_from(User)
                .where(User.is_service_account.is_(False))
            )
        ).scalar_one()
    )
    if total > _ROSTER_EXPORT_LIMIT:
        raise RosterExportTooLarge(
            f"the roster has {total} people (limit {_ROSTER_EXPORT_LIMIT}); "
            "export it through the API in pages instead"
        )

    rows = (
        (
            await session.execute(
                select(User)
                .options(selectinload(User.memberships))
                # Service accounts are not people and have no place on a
                # roster. Re-importing one would try to create a person under
                # an address an automation identity already holds.
                .where(User.is_service_account.is_(False))
                .order_by(User.created_at.asc(), User.id.asc())
            )
        )
        .scalars()
        .unique()
        .all()
    )

    header = ["email", "full_name", "team_id", "role", "is_active", "last_login_at"]
    out = [CSV_BOM + csv_line(header)]
    for user in rows:
        # Deterministic rather than whichever row the loader returned first:
        # a file that lists a different team for the same person on two
        # consecutive exports is one an administrator cannot diff.
        membership = min(
            user.memberships, key=lambda m: str(m.team_id), default=None
        )
        out.append(
            csv_line(
                [
                    user.email,
                    user.full_name,
                    membership.team_id if membership else None,
                    membership.role if membership else None,
                    user.is_active,
                    user.last_login_at,
                ]
            )
        )

    log.info("admin.user.exported", actor_id=str(actor.id), row_count=len(rows))
    return "".join(out)
