"""
Remediation pull-request service — v2.2 2.2-b3 (opt-in automated npm PR).

This is the b-track capstone. Unlike b2 (``services.remediation_service``),
which computes a side-effect-free dry-run, b3 actually WRITES to a customer's
GitHub repository: it creates a branch, commits the edited ``package.json``, and
opens a pull request, using a short-lived GitHub App installation token minted
by b1 (``services.github_app_service.mint_installation_token``).

Because that is a privileged external write, this module is defensive by design.

Security model (read this before touching the GitHub write path):

  1. **Opt-in is the only authority over the target repo.** The repository is
     NEVER chosen by the caller. ``create_npm_remediation_pr`` resolves the
     project's opted-in ``GitHubAppInstallation`` row (the ``project_id`` link, a
     NON-revoked credential, and a set ``repository_full_name``) and derives the
     target repo + installation token from THAT row only. If the project is not
     opted in (no such installation), the request is REFUSED (409) — we never
     open a PR on a repo the project is not explicitly linked to. There is no
     request field that lets a caller name a repo.

  2. **RBAC: team_admin of the project's team.** Opening a PR is a write to an
     external system, so it requires team_admin (not just developer). Existence-
     hide: a caller who cannot see the project gets the same 404 as a missing
     one (no cross-team enumeration). The read endpoint (``list_remediation_prs``)
     is any team member.

  3. **Re-validate everything at the trust boundary.** Even though
     ``repository_full_name`` is stored, it is re-validated to the exact
     ``owner/repo`` shape before it is interpolated into a GitHub URL
     (path-injection guard). The created branch name is built from a hex
     fingerprint we control (never from untrusted input) and re-validated to a
     safe ref charset. The manifest path is fixed (``package.json``) — the
     commit is scoped to that single file.

  4. **The installation token / App JWT NEVER touch a log or the response.** We
     log ids, repo, branch, and GitHub HTTP STATUS codes only — never response
     bodies (they may carry rate-limit / account detail) and never the token.

  5. **No network in tests.** Every GitHub call goes through an injectable
     ``http_client`` with ``follow_redirects=False`` and a bounded timeout. A
     redirect from GitHub is treated as an error (the token must never follow a
     3xx to an attacker-controlled host).

  6. **Idempotency.** The bump set is hashed to a stable ``change_fingerprint``;
     an existing ``open`` PR with the same fingerprint short-circuits and is
     returned instead of opening a duplicate. A partial unique index backstops
     a concurrent race.

CLAUDE.md compliance: core rule #2 (this ships migration 0021 + the model),
#11 (``os.getenv`` at call time via the config accessors), #12 (the router
requires JWT; the service re-asserts team_admin), §4 (typed domain exceptions →
RFC 7807), §5 (structlog JSON, never secrets).
"""

from __future__ import annotations

import base64
import hashlib
import re
import uuid
from dataclasses import dataclass

import httpx
import structlog
from sqlalchemy import select
from sqlalchemy.exc import IntegrityError
from sqlalchemy.ext.asyncio import AsyncSession

from core.audit import bind_audit_team
from core.config import (
    github_api_url,
    github_app_token_http_timeout_seconds,
)
from core.security import CurrentUser
from models import (
    GitHubAppCredential,
    GitHubAppInstallation,
    Project,
    RemediationPullRequest,
)
from services.remediation_service import (
    DryRunResult,
    ProjectNotAccessible,
    RemediationError,
    compute_npm_dry_run,
)

log = structlog.get_logger("remediation_pr.service")

# The single manifest file the commit is scoped to. b3 edits ONLY package.json
# (the lockfile is regenerated by the developer via `npm install` — surfaced as a
# warning). Keeping this fixed means the commit can never touch another path.
_NPM_MANIFEST_PATH = "package.json"

# A GitHub "owner/repo" full name. Each segment is the GitHub-allowed identifier
# charset (alnum, hyphen, underscore, dot) — re-validated at the trust boundary
# before URL interpolation even though it was stored, so a corrupted/crafted row
# can never smuggle a path-traversal or CRLF into the GitHub URL.
_REPO_FULL_NAME_RE = re.compile(r"^[A-Za-z0-9._-]{1,100}/[A-Za-z0-9._-]{1,100}$")

# A git ref segment we build ourselves (constant prefix + hex fingerprint). The
# fingerprint is hex so this always matches; re-validating is a belt for the
# "never interpolate an unvalidated value into a URL/ref" rule.
_BRANCH_NAME_RE = re.compile(r"^[A-Za-z0-9._/-]{1,200}$")

_GITHUB_ACCEPT = "application/vnd.github+json"
_GITHUB_API_VERSION = "2022-11-28"


# ---------------------------------------------------------------------------
# Domain exceptions (RFC 7807 — reuse the b2 base so the router maps once)
# ---------------------------------------------------------------------------


class ProjectNotOptedIn(RemediationError):
    """409 — the project has no opted-in, usable GitHub App installation.

    A credential alone does NOT authorise a write: a team must explicitly link an
    installation (with a repository) to the project first. Surfaced as 409 (a
    precondition the caller can satisfy by opting in) rather than 404 — the
    project itself is visible to the caller (team_admin), only the opt-in is
    missing.
    """

    status_code = 409
    title = "Project Not Opted In"
    type_uri = "https://docs.trustedoss.io/errors/remediation-not-opted-in"


class RemediationForbidden(RemediationError):
    """403 — the caller is a project member but not a team_admin."""

    status_code = 403
    title = "Forbidden"
    type_uri = "https://docs.trustedoss.io/errors/remediation-forbidden"


class RemediationConfigError(RemediationError):
    """422 — a stored value is unusable (e.g. malformed repository_full_name)."""

    status_code = 422
    title = "Remediation Configuration Unusable"
    type_uri = "https://docs.trustedoss.io/errors/remediation-config"


class GitHubWriteError(RemediationError):
    """502 — a GitHub write (branch / commit / PR) failed.

    The message carries the failing STEP + STATUS code only — never the GitHub
    response body or any token material.
    """

    status_code = 502
    title = "GitHub Write Failed"
    type_uri = "https://docs.trustedoss.io/errors/remediation-github-write"


# ---------------------------------------------------------------------------
# Result container
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class RemediationPRResult:
    """The outcome of a create-PR request.

    ``record`` is the persisted row (``None`` only when there was nothing to do —
    no recommendations / no manifest change). ``created`` is ``True`` when a NEW
    PR was opened, ``False`` when an existing open PR was returned (idempotent
    hit) or there was nothing to do. ``no_op_reason`` explains a ``None`` record.
    """

    record: RemediationPullRequest | None
    created: bool
    no_op_reason: str | None = None


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _is_super_admin(actor: CurrentUser) -> bool:
    return actor.is_superuser or actor.role == "super_admin"


def _is_team_admin(actor: CurrentUser, team_id: uuid.UUID) -> bool:
    if _is_super_admin(actor):
        return True
    return actor.team_roles.get(team_id) == "team_admin"


def _is_team_member(actor: CurrentUser, team_id: uuid.UUID) -> bool:
    if _is_super_admin(actor):
        return True
    return team_id in actor.team_ids


def _applied_bumps(result: DryRunResult) -> list[tuple[str, str | None, str]]:
    """Extract the bumps that ACTUALLY changed, as sorted ``(pkg, from, to)``.

    Drives both the persisted ``package_changes`` and the idempotency
    fingerprint. We key off the ``changes`` the adapter reported as ``changed``
    (a recommendation whose range already satisfied the target is NOT a bump) and
    join the advisory ``current`` version from the recommendation list.
    """
    current_by_pkg = {rec.package: rec.current_version for rec in result.recommendations}
    target_by_pkg = {rec.package: rec.recommended_version for rec in result.recommendations}
    bumps: list[tuple[str, str | None, str]] = []
    for change in result.changes:
        if not change.changed:
            continue
        target = target_by_pkg.get(change.package)
        if target is None:
            # The change came from a recommendation; if we cannot resolve a
            # target version, skip it rather than fabricate one.
            continue
        bumps.append((change.package, current_by_pkg.get(change.package), target))
    # Sort by package name for a STABLE fingerprint regardless of dict ordering.
    bumps.sort(key=lambda b: b[0])
    return bumps


def _fingerprint(bumps: list[tuple[str, str | None, str]]) -> str:
    """Stable hex digest of the ``(package, to)`` bump set.

    Only ``package`` + ``to`` (target) participate — the advisory ``from``
    version does not change the semantic edit, so two requests that bump the same
    packages to the same targets share a fingerprint (idempotent) even if the
    scan-observed current version drifted.
    """
    canonical = "\n".join(f"{pkg}@{to}" for pkg, _from, to in bumps)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()


def _package_changes_json(
    bumps: list[tuple[str, str | None, str]],
) -> list[dict[str, str | None]]:
    """Project the bump set to the JSONB shape stored on the row."""
    return [{"package": pkg, "from": frm, "to": to} for pkg, frm, to in bumps]


def _validate_repo_full_name(repository_full_name: str) -> tuple[str, str]:
    """Re-validate a stored ``owner/repo`` and return ``(owner, repo)``.

    Raises :class:`RemediationConfigError` (422) on a malformed value. Called
    BEFORE the value is interpolated into a GitHub URL so a corrupted / crafted
    row can never smuggle a traversal / CRLF / scheme into the request URL.
    """
    if not isinstance(repository_full_name, str) or not _REPO_FULL_NAME_RE.match(
        repository_full_name
    ):
        raise RemediationConfigError(
            "the opted-in installation's repository_full_name is not a valid "
            "'owner/repo' identifier"
        )
    owner, repo = repository_full_name.split("/", 1)
    return owner, repo


def _validate_branch_name(branch: str) -> None:
    """Belt-and-braces check on a ref name we build before interpolating it."""
    if not _BRANCH_NAME_RE.match(branch):  # pragma: no cover — fingerprint is hex
        raise RemediationConfigError("computed branch name is not a safe git ref")


# ---------------------------------------------------------------------------
# Opt-in resolution (the security gate)
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class _OptIn:
    """The resolved opt-in context the write derives everything from."""

    installation_row_id: uuid.UUID
    installation_id: str  # GitHub's numeric installation id (string)
    credential_id: uuid.UUID
    repository_full_name: str


async def _resolve_project_team_admin(
    session: AsyncSession,
    *,
    project_id: uuid.UUID,
    actor: CurrentUser,
) -> Project:
    """Load the project, enforcing existence-hide + team_admin RBAC.

    A caller who cannot see the project gets 404 (existence-hide, no cross-team
    enumeration). A member who is not team_admin gets 403.
    """
    project = (
        await session.execute(select(Project).where(Project.id == project_id))
    ).scalar_one_or_none()
    if project is None or not _is_team_member(actor, project.team_id):
        raise ProjectNotAccessible(f"project {project_id} not found")
    if not _is_team_admin(actor, project.team_id):
        raise RemediationForbidden(
            "opening a remediation PR requires team_admin of the project's team"
        )
    return project


async def _resolve_opt_in(
    session: AsyncSession,
    *,
    project_id: uuid.UUID,
) -> _OptIn:
    """Resolve the project's opted-in, usable installation, else 409.

    Usable means: an installation linked to THIS project, whose credential is
    NOT revoked, and which carries a ``repository_full_name``. The target repo +
    token are derived from this row ONLY — there is no caller-supplied repo.
    """
    row = (
        await session.execute(
            select(GitHubAppInstallation, GitHubAppCredential)
            .join(
                GitHubAppCredential,
                GitHubAppCredential.id == GitHubAppInstallation.credential_id,
            )
            .where(GitHubAppInstallation.project_id == project_id)
            .where(GitHubAppInstallation.repository_full_name.is_not(None))
            .where(GitHubAppCredential.revoked_at.is_(None))
            .order_by(GitHubAppInstallation.created_at.desc())
        )
    ).first()
    if row is None:
        raise ProjectNotOptedIn(
            "project is not opted in to automated remediation PRs: link a GitHub "
            "App installation (with a repository) to this project first"
        )
    installation, credential = row
    # repository_full_name is guaranteed non-NULL by the WHERE clause above.
    assert installation.repository_full_name is not None  # noqa: S101 — invariant
    return _OptIn(
        installation_row_id=installation.id,
        installation_id=installation.installation_id,
        credential_id=credential.id,
        repository_full_name=installation.repository_full_name,
    )


# ---------------------------------------------------------------------------
# GitHub write path (every call follow_redirects=False, status-only logging)
# ---------------------------------------------------------------------------


async def _github_get_base_ref_sha(
    client: httpx.AsyncClient,
    *,
    token: str,
    owner: str,
    repo: str,
    base_branch: str,
    timeout: float,
) -> str:
    """GET the base branch ref and return its commit SHA."""
    url = f"{github_api_url()}/repos/{owner}/{repo}/git/ref/heads/{base_branch}"
    resp = await _github_request(
        client, "GET", url, token=token, timeout=timeout, step="get_base_ref"
    )
    payload = resp.json()
    try:
        return str(payload["object"]["sha"])
    except (KeyError, TypeError) as exc:
        raise GitHubWriteError("GitHub returned an unexpected base-ref shape") from exc


async def _github_create_branch(
    client: httpx.AsyncClient,
    *,
    token: str,
    owner: str,
    repo: str,
    head_branch: str,
    base_sha: str,
    timeout: float,
) -> None:
    """Create the head branch pointing at ``base_sha``."""
    url = f"{github_api_url()}/repos/{owner}/{repo}/git/refs"
    body = {"ref": f"refs/heads/{head_branch}", "sha": base_sha}
    await _github_request(
        client, "POST", url, token=token, json=body, timeout=timeout, step="create_branch"
    )


async def _github_get_file_sha(
    client: httpx.AsyncClient,
    *,
    token: str,
    owner: str,
    repo: str,
    path: str,
    ref: str,
    timeout: float,
) -> str | None:
    """Return the blob SHA of ``path`` on ``ref``, or ``None`` if absent.

    The PUT contents API needs the existing blob SHA to UPDATE a file (omitting
    it CREATEs). A 404 here means the file does not yet exist on that branch.
    """
    url = f"{github_api_url()}/repos/{owner}/{repo}/contents/{path}?ref={ref}"
    resp = await _github_request(
        client,
        "GET",
        url,
        token=token,
        timeout=timeout,
        step="get_file_sha",
        allow_404=True,
    )
    if resp.status_code == 404:
        return None
    payload = resp.json()
    sha = payload.get("sha") if isinstance(payload, dict) else None
    return str(sha) if sha is not None else None


async def _github_put_manifest(
    client: httpx.AsyncClient,
    *,
    token: str,
    owner: str,
    repo: str,
    path: str,
    branch: str,
    content_text: str,
    file_sha: str | None,
    commit_message: str,
    timeout: float,
) -> None:
    """Commit the edited manifest to ``branch`` (scoped to ``path`` only)."""
    url = f"{github_api_url()}/repos/{owner}/{repo}/contents/{path}"
    encoded = base64.b64encode(content_text.encode("utf-8")).decode("ascii")
    body: dict[str, str] = {
        "message": commit_message,
        "content": encoded,
        "branch": branch,
    }
    if file_sha is not None:
        body["sha"] = file_sha
    await _github_request(
        client, "PUT", url, token=token, json=body, timeout=timeout, step="put_manifest"
    )


async def _github_open_pr(
    client: httpx.AsyncClient,
    *,
    token: str,
    owner: str,
    repo: str,
    head_branch: str,
    base_branch: str,
    title: str,
    body_text: str,
    timeout: float,
) -> tuple[int, str]:
    """Open the PR and return ``(number, html_url)``."""
    url = f"{github_api_url()}/repos/{owner}/{repo}/pulls"
    body = {"title": title, "head": head_branch, "base": base_branch, "body": body_text}
    resp = await _github_request(
        client, "POST", url, token=token, json=body, timeout=timeout, step="open_pr"
    )
    payload = resp.json()
    try:
        return int(payload["number"]), str(payload["html_url"])
    except (KeyError, TypeError, ValueError) as exc:
        raise GitHubWriteError("GitHub returned an unexpected pull-request shape") from exc


async def _github_request(
    client: httpx.AsyncClient,
    method: str,
    url: str,
    *,
    token: str,
    timeout: float,
    step: str,
    json: dict[str, str] | None = None,
    allow_404: bool = False,
) -> httpx.Response:
    """Issue one GitHub request defensively.

    Contract: ``follow_redirects=False`` (the installation token must never
    follow a 3xx to an attacker-controlled host); status-only logging (never the
    response body or the token); a non-2xx (other than an allowed 404) raises
    :class:`GitHubWriteError` carrying the STEP + STATUS only.
    """
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": _GITHUB_ACCEPT,
        "X-GitHub-Api-Version": _GITHUB_API_VERSION,
    }
    try:
        resp = await client.request(
            method,
            url,
            headers=headers,
            json=json,
            timeout=timeout,
            follow_redirects=False,
        )
    except httpx.HTTPError as exc:
        log.warning("remediation_pr.github_unreachable", step=step)
        raise GitHubWriteError(f"could not reach GitHub during '{step}'") from exc

    if allow_404 and resp.status_code == 404:
        return resp

    # A redirect must NOT be followed (we disabled it) and is not a success — the
    # token could otherwise be replayed against the redirect target.
    if resp.is_redirect or resp.status_code not in (200, 201):
        log.warning(
            "remediation_pr.github_write_non_2xx",
            step=step,
            status_code=resp.status_code,
        )
        raise GitHubWriteError(
            f"GitHub returned status {resp.status_code} during '{step}'"
        )
    return resp


# ---------------------------------------------------------------------------
# Public entry points
# ---------------------------------------------------------------------------


async def create_npm_remediation_pr(
    session: AsyncSession,
    actor: CurrentUser,
    project_id: uuid.UUID,
    *,
    manifest_override: str | None = None,
    http_client: httpx.AsyncClient | None = None,
) -> RemediationPRResult:
    """Open (or return the existing) automated npm remediation PR for a project.

    Steps (each gated / defensive — see the module docstring):
      1. RBAC: team_admin of the project's team (existence-hide on no access).
      2. Resolve the project's OPT-IN installation (target repo derived here,
         NEVER from the caller) — 409 if not opted in.
      3. Compute the b2 dry-run (the single source of the proposed edit). No
         changes → no-op result (do not open an empty PR).
      4. Idempotency: an existing ``open`` PR with the same fingerprint is
         returned (no duplicate).
      5. Persist a ``creating`` row, mint the installation token, perform the
         GitHub writes (branch → commit → PR) with ``follow_redirects=False``,
         flip the row to ``open`` (or ``failed``).
    """
    project = await _resolve_project_team_admin(
        session, project_id=project_id, actor=actor
    )
    opt_in = await _resolve_opt_in(session, project_id=project_id)

    # b2 is the single source of the proposed edit — never recompute it here.
    dry_run = await compute_npm_dry_run(
        session, actor, project_id, manifest_override=manifest_override
    )
    if not dry_run.changed or dry_run.edited_manifest is None:
        log.info(
            "remediation_pr.no_op",
            project_id=str(project_id),
            reason="no_manifest_change",
        )
        return RemediationPRResult(
            record=None, created=False, no_op_reason="no_manifest_change"
        )

    bumps = _applied_bumps(dry_run)
    if not bumps:
        return RemediationPRResult(
            record=None, created=False, no_op_reason="no_applied_bumps"
        )
    fingerprint = _fingerprint(bumps)

    # Idempotency: an OPEN PR with this fingerprint already exists → return it.
    existing = (
        await session.execute(
            select(RemediationPullRequest)
            .where(RemediationPullRequest.project_id == project_id)
            .where(RemediationPullRequest.change_fingerprint == fingerprint)
            .where(RemediationPullRequest.status == "open")
            .order_by(RemediationPullRequest.created_at.desc())
        )
    ).scalars().first()
    if existing is not None:
        log.info(
            "remediation_pr.idempotent_hit",
            project_id=str(project_id),
            remediation_pr_id=str(existing.id),
        )
        return RemediationPRResult(record=existing, created=False)

    # Re-validate the STORED repo before any URL interpolation (path-injection
    # guard) and build the branch name from the hex fingerprint we control.
    owner, repo = _validate_repo_full_name(opt_in.repository_full_name)
    head_branch = f"trustedoss/remediation-{fingerprint[:8]}"
    _validate_branch_name(head_branch)

    # Persist a 'creating' row BEFORE the writes so a crash mid-flight leaves a
    # visible trail (no silent partial). Bind the audit team for the commit.
    bind_audit_team(project.team_id)
    record = RemediationPullRequest(
        project_id=project_id,
        installation_row_id=opt_in.installation_row_id,
        ecosystem="npm",
        repository_full_name=opt_in.repository_full_name,
        head_branch=head_branch,
        base_branch="",  # filled once we read the default branch / base ref
        status="creating",
        package_changes=_package_changes_json(bumps),
        change_fingerprint=fingerprint,
        created_by_user_id=actor.id,
    )
    session.add(record)
    try:
        await session.commit()
    except IntegrityError:
        # Lost the lock race: a concurrent request already inserted a 'creating'
        # (or flipped to 'open') row for this fingerprint, and the partial unique
        # index (covering creating|open) rejected our INSERT. Re-read and return
        # the winner idempotently — crucially BEFORE any GitHub work, so two
        # racing requests never open two real PRs.
        await session.rollback()
        winner = (
            await session.execute(
                select(RemediationPullRequest)
                .where(RemediationPullRequest.project_id == project_id)
                .where(RemediationPullRequest.change_fingerprint == fingerprint)
                .where(RemediationPullRequest.status.in_(("creating", "open")))
                .order_by(RemediationPullRequest.created_at.desc())
            )
        ).scalars().first()
        if winner is not None:
            log.info(
                "remediation_pr.lock_race_idempotent_hit",
                project_id=str(project_id),
                remediation_pr_id=str(winner.id),
            )
            return RemediationPRResult(record=winner, created=False)
        raise
    await session.refresh(record)

    base_branch = (project.default_branch or "main").strip() or "main"

    try:
        token_info = await _mint_token(session, opt_in, http_client=http_client)
        token = token_info["token"]
        timeout = github_app_token_http_timeout_seconds()
        owns_client = http_client is None
        client = http_client or httpx.AsyncClient(timeout=timeout)
        try:
            base_sha = await _github_get_base_ref_sha(
                client,
                token=token,
                owner=owner,
                repo=repo,
                base_branch=base_branch,
                timeout=timeout,
            )
            await _github_create_branch(
                client,
                token=token,
                owner=owner,
                repo=repo,
                head_branch=head_branch,
                base_sha=base_sha,
                timeout=timeout,
            )
            file_sha = await _github_get_file_sha(
                client,
                token=token,
                owner=owner,
                repo=repo,
                path=_NPM_MANIFEST_PATH,
                ref=base_branch,
                timeout=timeout,
            )
            await _github_put_manifest(
                client,
                token=token,
                owner=owner,
                repo=repo,
                path=_NPM_MANIFEST_PATH,
                branch=head_branch,
                content_text=dry_run.edited_manifest,
                file_sha=file_sha,
                commit_message=_commit_message(bumps),
                timeout=timeout,
            )
            pr_number, pr_url = await _github_open_pr(
                client,
                token=token,
                owner=owner,
                repo=repo,
                head_branch=head_branch,
                base_branch=base_branch,
                title=_pr_title(bumps),
                body_text=_pr_body(bumps, dry_run),
                timeout=timeout,
            )
        finally:
            if owns_client:
                await client.aclose()
            # Drop the token reference promptly — it must not linger.
            del token
    except RemediationError:
        # A GitHub write (or token mint) failed: flip the row to 'failed' so the
        # attempt is auditable, then re-raise the typed error for the router.
        bind_audit_team(project.team_id)
        record.status = "failed"
        record.base_branch = base_branch
        await session.commit()
        await session.refresh(record)
        raise

    # Success: record the PR coordinates and flip to 'open'.
    bind_audit_team(project.team_id)
    record.status = "open"
    record.base_branch = base_branch
    record.pr_number = pr_number
    record.pr_url = pr_url
    await session.commit()
    await session.refresh(record)

    log.info(
        "remediation_pr.opened",
        project_id=str(project_id),
        remediation_pr_id=str(record.id),
        repository_full_name=opt_in.repository_full_name,
        head_branch=head_branch,
        base_branch=base_branch,
        pr_number=pr_number,
        bump_count=len(bumps),
    )
    return RemediationPRResult(record=record, created=True)


async def _mint_token(
    session: AsyncSession,
    opt_in: _OptIn,
    *,
    http_client: httpx.AsyncClient | None,
) -> dict[str, str]:
    """Mint the installation token via b1, mapping its errors to b3 domain errors.

    b1's ``mint_installation_token`` raises ``GitHubAppError`` subclasses; we wrap
    them in :class:`GitHubWriteError` so the b3 router maps a single error family.
    The token is returned but NEVER logged here (b1 already logs only its expiry).
    """
    from services.github_app_service import (
        GitHubAppError,
        mint_installation_token,
    )

    try:
        result = await mint_installation_token(
            session,
            opt_in.credential_id,
            opt_in.installation_id,
            http_client=http_client,
        )
    except GitHubAppError as exc:
        # Status-only context; b1 already logged the specifics without secrets.
        log.warning("remediation_pr.token_mint_failed", credential_id=str(opt_in.credential_id))
        raise GitHubWriteError(
            "could not mint a GitHub App installation token for the opted-in repo"
        ) from exc
    return {"token": str(result["token"]), "expires_at": str(result.get("expires_at", ""))}


def _commit_message(bumps: list[tuple[str, str | None, str]]) -> str:
    if len(bumps) == 1:
        pkg, _frm, to = bumps[0]
        return f"chore(deps): bump {pkg} to {to} (TrustedOSS remediation)"
    return f"chore(deps): bump {len(bumps)} vulnerable dependencies (TrustedOSS remediation)"


def _pr_title(bumps: list[tuple[str, str | None, str]]) -> str:
    if len(bumps) == 1:
        pkg, _frm, to = bumps[0]
        return f"[TrustedOSS] Bump {pkg} to {to}"
    return f"[TrustedOSS] Bump {len(bumps)} vulnerable npm dependencies"


def _pr_body(bumps: list[tuple[str, str | None, str]], dry_run: DryRunResult) -> str:
    """Human-readable PR description. NEVER includes secrets — bumps only."""
    lines = [
        "This pull request was opened automatically by **TrustedOSS** to "
        "remediate known vulnerabilities in your npm dependencies.",
        "",
        "### Dependency bumps",
        "",
        "| Package | From | To |",
        "| --- | --- | --- |",
    ]
    for pkg, frm, to in bumps:
        lines.append(f"| `{pkg}` | {frm or '?'} | {to} |")
    lines.append("")
    if any(w.code == "lockfile_regeneration_required" for w in dry_run.warnings):
        lines.append(
            "> :warning: **Lockfile not updated.** Only `package.json` was edited. "
            "Run `npm install` to regenerate `package-lock.json` before merging."
        )
    lines.append("")
    lines.append("_Review the changes carefully before merging._")
    return "\n".join(lines)


async def list_remediation_prs(
    session: AsyncSession,
    actor: CurrentUser,
    project_id: uuid.UUID,
    *,
    page: int = 1,
    page_size: int = 50,
) -> tuple[list[RemediationPullRequest], int]:
    """List a project's remediation-PR records (newest first).

    RBAC: any team member (read). Existence-hide on no access (404). Mirrors the
    pagination shape of ``github_app_service.list_installations``.
    """
    project = (
        await session.execute(select(Project).where(Project.id == project_id))
    ).scalar_one_or_none()
    if project is None or not _is_team_member(actor, project.team_id):
        raise ProjectNotAccessible(f"project {project_id} not found")

    page = max(page, 1)
    page_size = max(min(page_size, 200), 1)

    from sqlalchemy import func

    base = select(RemediationPullRequest).where(
        RemediationPullRequest.project_id == project_id
    )
    count_base = (
        select(func.count())
        .select_from(RemediationPullRequest)
        .where(RemediationPullRequest.project_id == project_id)
    )
    total = int((await session.execute(count_base)).scalar_one())
    rows_stmt = (
        base.order_by(
            RemediationPullRequest.created_at.desc(),
            RemediationPullRequest.id.desc(),
        )
        .limit(page_size)
        .offset((page - 1) * page_size)
    )
    rows = list((await session.execute(rows_stmt)).scalars().all())
    return rows, total


__all__ = [
    "GitHubWriteError",
    "ProjectNotOptedIn",
    "RemediationConfigError",
    "RemediationForbidden",
    "RemediationPRResult",
    "create_npm_remediation_pr",
    "list_remediation_prs",
]
